{{- define "app-library.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
data: {}
{{- end -}}
{{- define "app-library.configmap" -}}
{{- include "app-library.util.merge" (append . "app-library.configmap.tpl") -}}
{{- end -}}